# This is a config for E2B sandbox template.
# You can use template ID (ixknpdztqwfnavtt3kqs) or template name (gitwit-desktop) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("gitwit-desktop") # Sync sandbox
# sandbox = await AsyncSandbox.create("gitwit-desktop") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('gitwit-desktop')

team_id = '"d610ca28-d4db-49e5-b977-86342d8036f2"'
memory_mb = 1_024
cpu_count = 2
dockerfile = "d0cafc2d-38e9-4355-b1f5-ee58ef4b615c.Dockerfile"
template_name = "gitwit-desktop"
template_id = "ixknpdztqwfnavtt3kqs"
